DEV="device/malata/k1002"

# Generate AndroidProducts.mk
echo "# Auto-Generated by ${DEV}/setup.sh" >${DEV}/AndroidProducts.mk
echo "PRODUCT_MAKEFILES += \$(LOCAL_DIR)/"$VENDOR"_${DEV}.mk" >>${DEV}/AndroidProducts.mk

# Generate <vendor>_${DEVICE}.mk
echo "# Auto-Generated by ${DEV}/setup.sh" >${DEV}/"$VENDOR"_${DEV}.mk
echo "\$(call inherit-product, ${DEV}/full_${DEV}.mk)" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "\$(call inherit-product, vendor/"$VENDOR"/config/common_full_tablet_wifionly.mk)" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "PRODUCT_NAME := "$VENDOR"_${DEV}" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "# Additional Props" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "TARGET_FACE_UNLOCK_SUPPORTED := true" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "TARGET_BOOT_ANIMATION_RES := 720" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "PRODUCT_GMS_CLIENTID_BASE := android-malata" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "PRODUCT_BUILD_PROP_OVERRIDES += \" >>${DEV}/"$VENDOR"_${DEV}.mk
echo "    PRODUCT_NAME=k1002" >>${DEV}/"$VENDOR"_${DEV}.mk